### PR TITLE
Update azure.yaml template name and metadata

### PR DESCRIPTION
**Pull request by kristenwomack**
## Purpose
I updated the template name and meta data `template` to match the repo name. This is required for `azd`.

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[  ] Other... Please describe:
```

### CODE REVIEW

**Comment by kristenwomack** [comment]
@gkulin @anfibiacreativa - are there other places the template name needs to be updated after changing the repo name? Tagged y'all for review.

**Comment by marlenezw** [comment]
Hi @kristenwomack, this looks good to me. Let me know if you'd like me to merge it

**Comment by kristenwomack** [comment]
> Hi @kristenwomack, this looks good to me. Let me know if you'd like me to merge it

Yes, please - thank you!

**Comment by marlenezw** [comment]
Someone already made these changes. Thank you

**Pull request closed without merging**
